version: '3'

services:
    mysql:
        build: ./
        container_name: mysql
        tty: true
        ports: 
            - "3306:3306"
        env_file:
            - ./default.env
        volumes:
            - "./data/mysql:/var/lib/mysql"
            - "./etc/mysql/my.cnf:/etc/mysql/my.cnf"
            - "./etc/mysql/conf.d:/etc/mysql/conf.d"
